services:
  db:
    image: mysql:9
    container_name: nestjs-db
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: database
      mysql_passowrd: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  api:
    container_name: nestjs
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/Dockerenv
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npx nest start --watch

volumes:
  db_data: